package classification.featureSelectors;

import weka.attributeSelection.ASEvaluation;
import weka.core.Instances;

public interface FeatureSelector {

	/**
	 * FilterData receives the parameter oldData, that represents the
	 * trainingSet before Feature Selection, and returns the Data filtered. Thus
	 * the classification can be done with the main attributes the filter has
	 * chosen.
	 * 
	 * @param oldData
	 * @return
	 */
	public Instances filterData(Instances oldData);

	/**
	 * setMaxNumFeatures receives a integer that represents the maximum number
	 * of features we expect to receive from the filter.
	 * 
	 * @param maxNumFeatures
	 */
	public void setMaxNumFeatures(int maxNumFeatures);

	/**
	 * getEvaluator gets and returns the evaluation algorithm, that is
	 * responsible for evaluate the trainingSet and returns the main attributes
	 * to a classification.
	 * 
	 * @return
	 */
	public ASEvaluation getEvaluator();

	/**
	 * Returns the evaluation algorithm name.
	 * 
	 * @return
	 */
	public String evaluationAlgorithmName();

	/**
	 * Gets and return a String generated by Weka(R) class "AttributeSelection".
	 * 
	 * @return
	 */
	public String getFeatSelResults();

}
